apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
    #  namespace: production
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
         claimName: mysql-pvc
      containers:
      - name: backend
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/tmp/data"
          name: mysql-pv-storage
