apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
    #  namespace: production
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
